name: Feature Request
description: 添加一个功能/Suggest an idea for this project
title: "[FR] 在这里描述你的功能/Describe your feature here",
labels: ["enhancement"]
assignees:
  - lingfengyu-dreaming
body:
  - type: checkboxes
    id: related-problem-check
    attributes:
      label: Is your feature request related to a problem?/你的功能和问题相关吗?
    options:
      - label: Yes
        required: false
      - label: No
        required: false
  - type: textarea
    id: related-problem
    attributes:
      label: If your feature request related to a problem, describe it here./如果你的功能和问题相关，在这里描述它。
      description: |
        Please describe the problem or link to it here.
        请描述你的问题或连接到它。
      placeholder: problem or #1
  - type: textarea
    id: describe-feature
    attributes:
      label: Describe your feature here./在这里描述你的功能。
    validations:
      required: true
  - type: checkboxes
    id: describe-feature-check
    attributes:
      label: Description/描述
      description: |
        I have describe my feature clearly.
        我已经清楚地描述了我的功能。
      options:
        - label: Yes
          required: false
        - label: No
          required: false
  - type: textarea
    id: additional-infomation
    attributes:
      label: Additional Infomation/附加信息
      description: |
        Any infomation need to attach.
        任何需要的信息。
      placeholder: |
        The infomation might be useful...
        可能有用的信息...
  - type: checkboxes
    id: last-check
    attributes:
      label: 检查清单 - Check list
      description: |
        Last check of your feature request.
        最后检查一次你的功能请求。
      options:
        - label: I have finished the title and delete the hints.(keep the [FR] there)/我已经填好了标题并且删除了提示文本。(保留[FR]在原处)
          required: false
        - label: I have clearly describe my feature./我已经清楚地描述了我想要的功能。
          required: false
        - label: I know it should be done by a theme./我知道这是主题应该完成的。
          required: false
        - label: It isn't a plugin feature./这不是一个插件功能。
          required: false
        - label: I doesn't check all the checkboxes and therefore I just checked all of them./我没有检查所有的复选框，只是闭眼选中了所有复选框。
          required: false
        - label: No plugin do this feature./没有插件完成这个功能。
          required: false
        - label: Not too hard for a theme to complete this feature./这个功能对主题来说不难实现。
          required: false

