name: package

on:
  push:
    paths: theme.json
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install deps
        run: npm install

      - name: Build scss
        run: npm run build

      - name: Package
        run: zip -r package.zip . -i 'theme.*' 'icon.png' 'preview.png' 'README*.md' 'resources/*' 'sub/*' -x '**/*.css.map'

      - name: Get current version
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq -r ".version" theme.json'

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: package.zip
          name: Release ${{ steps.version.outputs.value }}
          tag_name: ${{ steps.version.outputs.value }}
          make_latest: true
