name: package

on:
  push:
    branches:
      - scss
    paths:
      - theme.json
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0

      - name: Install deps
        run: pnpm install

      - name: Build scss
        run: pnpm run build

      - name: Package
        run: zip -r package.zip . -i 'theme.*' 'icon.png' 'preview.png' 'README*.md' 'resources/*' 'sub/*' -x '**/*.css.map' 'theme.css.map' 'theme.scss'

      - name: Get current version
        uses: emptylight370/jq-action@v1
        id: version
        with:
          data: theme.json
          filter: .version

      - name: Generate release log
        run: |
          git cliff -u -o release.md -t ${{ steps.version.outputs.result }}
          prettier -w release.md

      - name: Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          files: package.zip
          name: Release ${{ steps.version.outputs.result }}
          tag_name: ${{ steps.version.outputs.result }}
          make_latest: true
          body_path: release.md
