name: package

on:
  push:
    paths: theme.json
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v5

      - uses: volta-cli/action@v4

      - name: Install deps
        run: npm install

      - name: Build scss
        run: npm run build

      - name: Package
        run: zip -r package.zip . -i 'theme.*' 'icon.png' 'preview.png' 'README*.md' 'resources/*' 'sub/*' -x '**/*.css.map' 'theme.css.map' 'theme.scss'

      - name: Get current version
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq -r ".version" theme.json'

      - name: Generate release log
        run: |
          npm install conventional-changelog-cli
          npx conventional-changelog -o release.md -n conventional-changelog.config.json -k theme.json -c theme.json -r 2
          prettier -w release.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: package.zip
          name: Release ${{ steps.version.outputs.value }}
          tag_name: ${{ steps.version.outputs.value }}
          make_latest: true
          body_path: release.md
