name: package

on:
  push:
    paths: 'theme.json'
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-20.04

    permissions: 
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: package
        run: find ./ -name 'theme.json' -o -name 'icon.png' -o -name 'preview.png' -o -name 'README.md' -o -name 'README_zh_CN.md' -o -name 'theme.css' -o -name 'theme.js' -o -path './resources/*' -o -path './sub/*' | xargs zip package.zip

      - name: install
        run: sudo apt-get install jq
      
      - name: create tag
        run: echo "VERSION=$(jq -r ".version" theme.json)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: package.zip
          name: Release ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          make_latest: true